server:
  port: 8080

spring:
  config:
    activate:
      on-profile: deploy


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  batch:
    jdbc:
      initialize-schema: always


  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        enabled: true
        options:
          model: ${OPENAI_MODEL}
          temperature: ${OPENAI_TEMPERATURE}
          max-tokens: ${OPENAI_MAX_TOKENS}
          timeout: 60s

  main:
    allow-bean-definition-overriding: true

  data:
    redis:
      host: ${AWS_REDIS_HOST}
      port: 6379
      password: ${AWS_REDIS_PASSWORD}


jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: ${ACCESS_TOKEN_EXPIRATION_MINUTES}
  refresh-token-expiration-days: ${REFRESH_TOKEN_EXPIRATION_DAYS}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus,metrics
  endpoint:
    health:
      show-details: always

hantu-openapi:
  appkey: ${HANTU_APPKEY}
  appsecret: ${HANTU_APPSECRET}
  base-url: https://openapi.koreainvestment.com:9443

db-openapi:
  db-appkey: ${DB_APPKEY}
  db-appsecret: ${DB_APPSECRET}
  base-url: https://openapi.dbsec.co.kr:8443

eos:
  api-key: ${EOS_API_KEY}

firebase:
  config: ${FIREBASE_CONFIG}

websocket:
  server:
    url: ${WEBSOCKET_PRIVATE_HOST}
