plugins {
    id 'java'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

group = 'com.fintory'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

dependencies {


    implementation project(':common')
    implementation project(':domain')
    implementation project(':infra')
    implementation project(':auth')


    /* .env 자동 로딩 */
    implementation 'me.paulschwarz:spring-dotenv:4.0.0'

    /* db */
    runtimeOnly 'com.mysql:mysql-connector-j'

    /* jpa */
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    /* Web */
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    /* Security */
    implementation 'org.springframework.boot:spring-boot-starter-security'

    /* Spring Security OAuth2 Client */
    /* implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'*/

    /* lombok */
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    /* swagger */
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.8")

    /* Test */
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    /* Actuator */
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    /* Retry */
    implementation 'org.springframework.retry:spring-retry'

    /* WebSocket */
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework:spring-messaging'
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    /* Spring Batch */
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-quartz'

    /* Netty DNS Resolver */
    runtimeOnly("io.netty:netty-resolver-dns-native-macos:4.1.127.Final")

    /* Spring AOP */
    implementation 'org.springframework.boot:spring-boot-starter-aop'

    /* Micrometer(Prometheus) */
    implementation("io.micrometer:micrometer-registry-prometheus:1.15.2")


}

test {
    useJUnitPlatform()
}

bootJar {
    enabled = true
}

jar {
    enabled = false
}
